name: Create Release with Full Commit History

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get all commit messages since last release
      id: get_commits
      run: |
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        if [ -z "$TAG" ]; then
          echo "No previous tag found, listing all commits"
          COMMITS=$(git log --pretty=format:"%h %s")
        else
          echo "Previous tag: $TAG"
          COMMITS=$(git log $TAG..HEAD --pretty=format:"%h %s")
        fi
        echo "${COMMITS}"
        echo "::set-output name=commits::${COMMITS}"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release
          ${{ steps.get_commits.outputs.commits }}
        draft: false
        prerelease: false


